#!/bin/bash
#PBS -l nodes=1:ppn=24
#PBS -N gromacs_yzj
#PBS -o gromacs_jobs.out
#PBS -j oe

#
# The number of processors you desire is indicated by replacing
# <nproc> above.
#

#
# GROMACS path and arguments to mdrun :
#
cd $PBS_O_WORKDIR

if [ -d /program/gromacs/4.6.7-openmpi.gnu ]; then
    GROMACS_PATH=/program/gromacs/4.6.7-openmpi.gnu
    GROMPP_EXE=grompp_mpi
    MDRUN_EXE=mdrun_mpi
else 
    GROMACS_PATH=/home/software/programs/gromacs
    GROMPP_EXE=grompp
    MDRUN_EXE=mdrun
fi
source $GROMACS_PATH/bin/GMXRC.bash
OPENMPI_PATH=/program/mpi/openmpi/1.10.1-gnu
MPIRUN=${OPENMPI_PATH}/bin/mpirun
MPIEXEC=${OPENMPI_PATH}/bin/mpirun
export PATH=${OPENMPI_PATH}/bin:$PATH
export LD_LIBRARY_PATH=${OPENMPI_PATH}/lib:${LD_LIBRARY_PATH}

echo "============The computed nodes============"
cp    -f  $PBS_NODEFILE  NODE.txt
echo  "User:               " $USER
cat   $PBS_NODEFILE
echo  "Job ID:             " $PBS_JOBID
echo  "Job Cookie:         " $PBS_JOBCOOKIE
echo  "Using executable:   " `which mpirun`
echo "Using executable:   " `which ${GROMPP_EXE}`
echo "Using executable:   " `which ${MDRUN_EXE}`
echo  `date`
echo "============Finished setting=============="
TIME_DIR=$(date '+%Y-%m-%d_%H-%M-%S')
TIME_DIR="${USER}_jobs_${TIME_DIR}_${PBS_JOBID}"
if [ -d /utmp ]; then
    TEMP_DIR=/utmp/${USER}/${TIME_DIR}
else
    TEMP_DIR=/temp/${USER}/${TIME_DIR}
fi
mkdir -p ${TEMP_DIR}
cp -rf * ${TEMP_DIR}
cd ${TEMP_DIR}
rm -f gromacs_jobs.out
echo "The temp direcotry: " ${TEMP_DIR}
echo "============Finished setting=============="
# =============== Don't Change Above Setting ===================== #

echo "+++++++++++++ Run ++++++++++++++++++++++++++++"


genbox_mpi -cp /home/yinzj/zeolite/box/ITV/1/ITV.g96 -ci /home/yinzj/zeolite/g96/CH4_TraPPE.g96 -nmol 6900 -o box.g96

genbox_mpi -cp /home/yinzj/zeolite/box/ITV/1/ITV.g96 -ci /home/yinzj/zeolite/g96/CH4_TraPPE.g96 -nmol 6800 -o box.g96

genbox_mpi -cp /home/yinzj/zeolite/box/ITV/1/ITV.g96 -ci /home/yinzj/zeolite/g96/CH4_TraPPE.g96 -nmol 6700 -o box.g96

genbox_mpi -cp /home/yinzj/zeolite/box/ITV/1/ITV.g96 -ci /home/yinzj/zeolite/g96/CH4_TraPPE.g96 -nmol 6600 -o box.g96

genbox_mpi -cp /home/yinzj/zeolite/box/ITV/1/ITV.g96 -ci /home/yinzj/zeolite/g96/CH4_TraPPE.g96 -nmol 6500 -o box.g96

genbox_mpi -cp /home/yinzj/zeolite/box/ITV/1/ITV.g96 -ci /home/yinzj/zeolite/g96/CH4_TraPPE.g96 -nmol 6400 -o box.g96

genbox_mpi -cp /home/yinzj/zeolite/box/ITV/1/ITV.g96 -ci /home/yinzj/zeolite/g96/CH4_TraPPE.g96 -nmol 6300 -o box.g96

genbox_mpi -cp /home/yinzj/zeolite/box/ITV/1/ITV.g96 -ci /home/yinzj/zeolite/g96/CH4_TraPPE.g96 -nmol 6200 -o box.g96

genbox_mpi -cp /home/yinzj/zeolite/box/ITV/1/ITV.g96 -ci /home/yinzj/zeolite/g96/CH4_TraPPE.g96 -nmol 6100 -o box.g96

genbox_mpi -cp /home/yinzj/zeolite/box/ITV/1/ITV.g96 -ci /home/yinzj/zeolite/g96/CH4_TraPPE.g96 -nmol 6000 -o box.g96

genbox_mpi -cp /home/yinzj/zeolite/box/ITV/1/ITV.g96 -ci /home/yinzj/zeolite/g96/CH4_TraPPE.g96 -nmol 5900 -o box.g96

genbox_mpi -cp /home/yinzj/zeolite/box/ITV/1/ITV.g96 -ci /home/yinzj/zeolite/g96/CH4_TraPPE.g96 -nmol 5800 -o box.g96

genbox_mpi -cp /home/yinzj/zeolite/box/ITV/1/ITV.g96 -ci /home/yinzj/zeolite/g96/CH4_TraPPE.g96 -nmol 5700 -o box.g96

genbox_mpi -cp /home/yinzj/zeolite/box/ITV/1/ITV.g96 -ci /home/yinzj/zeolite/g96/CH4_TraPPE.g96 -nmol 5600 -o box.g96

genbox_mpi -cp /home/yinzj/zeolite/box/ITV/1/ITV.g96 -ci /home/yinzj/zeolite/g96/CH4_TraPPE.g96 -nmol 5500 -o box.g96

genbox_mpi -cp /home/yinzj/zeolite/box/ITV/1/ITV.g96 -ci /home/yinzj/zeolite/g96/CH4_TraPPE.g96 -nmol 5400 -o box.g96

genbox_mpi -cp /home/yinzj/zeolite/box/ITV/1/ITV.g96 -ci /home/yinzj/zeolite/g96/CH4_TraPPE.g96 -nmol 5300 -o box.g96

genbox_mpi -cp /home/yinzj/zeolite/box/ITV/1/ITV.g96 -ci /home/yinzj/zeolite/g96/CH4_TraPPE.g96 -nmol 5200 -o box.g96

genbox_mpi -cp /home/yinzj/zeolite/box/ITV/1/ITV.g96 -ci /home/yinzj/zeolite/g96/CH4_TraPPE.g96 -nmol 5100 -o box.g96

genbox_mpi -cp /home/yinzj/zeolite/box/ITV/1/ITV.g96 -ci /home/yinzj/zeolite/g96/CH4_TraPPE.g96 -nmol 5000 -o box.g96


echo "+++++++++++++ Finish  +++++++++++++++++++++++++"

cd $PBS_O_WORKDIR
cp -rf ${TEMP_DIR}/* .
rm -rf ${TEMP_DIR}


echo "All files were copied back!"
echo "The work direcotry: " $PBS_O_WORKDIR
echo `date`
echo "============Finished Job =============="

